import { Experience } from "@/lib/types";

export const experience: Experience[] = [
  {
    id: 0,
    title: "Product Designer",
    type: "Full-time",
    company: "Affordable SEO SaaS.",
    logo: "/images/logos/klikko.png",
    startDate: "March 24",
    endDate: null,
  },
  {
    id: 1,
    title: "UX Designer & Project Manager",
    type: "Contractor",
    company: "Cantilever: Websites & Product Design",
    logo: "/images/logos/cantilever.png",
    startDate: "Jan 22",
    endDate: "December 2026",
  },
  {
    id: 2,
    title: "Product Design Research",
    type: "Msc. Thesis",
    company: "Milestone Systems Denmark",
    logo: "/images/logos/milestone.png",
    startDate: "Jan 23",
    endDate: "Jun 24",
  },
  {
    id: 3,
    title: "User Experience Researcher",
    type: "Internship",
    company: "Aalborg University in Copenhagen (AAU)",
    logo: "/images/logos/AAU.png",
    startDate: "Sep 23",
    endDate: "Jan 24",
  },
  {
    id: 4,
    title: "Junior UX Designer",
    type: "Student",
    company: "Cantilever: Websites & Product Design",
    logo: "/images/logos/cantilever.png",
    startDate: "Dec 22",
    endDate: "Present",
  },
  {
    id: 1,
    title: "AdTech Product Specialist",
    type: "Full-time",
    company: "Trkken: Google Marketing Platform & Google Cloud ",
    logo: "/images/logos/trkken.png",
    startDate: "Oct 21",
    endDate: "Jan 23",
  },
  {
    id: 1,
    title: "Digital Marketing Specialist",
    type: "Internship",
    company: "GOLine Digital Agency ",
    logo: "/images/logos/goline.png",
    startDate: "May 20",
    endDate: "Jul 2021",
  },
];
