export const projects = [
  {
    id: 1,
    title: "UX Design",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "phone",
    color: "light-pink",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 2,
    title: "Design System",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "browser",
    color: "light-green",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 3,
    title: "Design System",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "mac",
    color: "light-orange",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 4,
    title: "UX Design",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "phone",
    color: "light-blue",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 5,
    title: "UX Design",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "phone",
    color: "light-pink",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 6,
    title: "Design System",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "browser",
    color: "light-green",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 7,
    title: "Design System",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "mac",
    color: "light-orange",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 8,
    title: "UX Design",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "phone",
    color: "light-blue",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
];

export const currentProjects = [
  {
    id: 5,
    title: "UX Design",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "browser",
    color: "black",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
  {
    id: 6,
    title: "Design System",
    description: "Lorem Ipsum",
    image: "https://via.placeholder.com/150",
    type: "phone",
    color: "white",
    company: "Element451.com",
    role: "UX Designer",
    team: ["Project Manager", "Developer", "QA", "Strategist"],
    duration: "30 hours",
    tools: ["figma", "figma", "figma"],
  },
];
