import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/shared/nav-bar";
import Footer from "@/components/shared/footer";
import { productSans } from "@/lib/custom-fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${productSans.className} antialiased flex flex-col text-white`}
      >
        <NavBar />
        <main className="flex flex-col items-center overflow-x-hidden min-h-[100vh]">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
